language: c
# To build on OSX, switch the previous line to
# language: objective-c

script: 
    - Rscript -e "require(knitr); fname = 'example.Snw'; knit(fname); purl(fname)"
    - pdflatex example

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh install_deps
env:
  global:
    - BOOTSTRAP_LATEX="1"    

